#!/usr/bin/env ruby
%w[vim vimrc gvimrc].each do |name|
  src = File.join(File.dirname(File.expand_path($0)), name)
  dst = File.join(File.expand_path('~'), '.' + name)
  if File.exists?(dst)
    if File.symlink?(dst) && File.readlink(dst) == src
      puts "Already installed #{src} -> #{dst}"
    else
      File.unlink(dst) 
    end
  else
    puts "Installing #{src} -> #{dst}"
    File.symlink(src, dst)
  end
end
