#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/janne/markdown.vim.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/tpope/vim-ragtag.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://git.wincent.com/command-t.git"
]

# Plugins not updated:
# zencoding, vim-autocomplpop, tabular, command-t

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "vim", "bundle")

FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  FileUtils.rm_rf dir
  `git clone #{url} #{dir}`
  if File.exists?("#{dir}/Rakefile")
    puts "  Building #{dir}"
    `cd #{dir}; rake make 2> /dev/null`
  end
end

# Update helptags
`vim -c "call pathogen#helptags()" -c "quit" 2> /dev/null`
